name: Channel Poster
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [eleven]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Install necessary dependencies for the script to work
      - name: Install Dep
        run: sudo pip install pyTelegramBotAPI
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          ref: eleven
     # Post the update
      - name: Bot
        run: sudo -E python3 .github/scripts/post.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT: ${{ secrets.CHAT_ID }}
     # Commit the changes and push to git
      - name: Commit and Push Changes
        run: sudo bash .github/scripts/push.sh